### ISSUE TITLE
Fence gates aren't ignored if placed on an air block

### ISSUE THREAD

**Issue by SullyTheUnusual** [Psychlist1972/Minecraft-DoorCloser#1]
Sneak + right-clicking to ignore doors/gates doesn't work if you have something in your hand (main or offhand).

**Comment by Psychlist1972** [comment]
Thanks. Saw this in the forums as well. It's not something I can change as the shift+place behavior is already assigned in Minecraft. I don't want to override that.

**Comment by Psychlist1972** [comment]
Closing as will-not-fix.
