### ISSUE TITLE
DoorCloser-1.0.3 with 1.13 Spigot not working

### ISSUE THREAD

**Issue by smmmadden** [Psychlist1972/Minecraft-DoorCloser#2]
Testing Spigot 1.13 with plugin does nothing - doors remain open after the default of 20 seconds.  No errors in-game or on console.  Most of the blocks have changed in 1.13, so this may be related to not having the correct name referenced in code and config.yml.

**Shano_dekono  Today at 8:17 AM** with Paper Spigot 1.13
yeah i tested it too i get this error in paper [DoorCloser] Tried to close the block, but instanceof Openable check failed.  Works fine in 1.12.2 Paper Spigot.

**Comment by smmmadden** [comment]
Tested with PaperSpigot build 192 (1.13.1) and doors/gates remain open and never close.  No errors in console/logs.  Using Java 1.8.0_181

**Comment by smmmadden** [comment]
Just checking in @Psychlist1972 to see if this can/will be updated for 1.13.1  Re-Tested with PaperSpigot build 229 today - no luck.
Thanks! -Steve

**Comment by Psychlist1972** [comment]
The latest snapshot supports 1.13.1 and also double doors. Thanks for your reports here and in the forum.
